"""add_task_events

Revision ID: d56fce9e1540
Revises: 60f03d1c892d
Create Date: 2026-10-02 19:22:45.086810

"""

import json
from datetime import datetime, timezone
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d56fce9e1540"
down_revision: Union[str, Sequence[str], None] = "60f03d1c892d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


STATUS_BY_EVENT_TYPE = {
    "created": "open",
    "offered": "pending",
    "approved": "approved",
    "rejected": "open",
    "closed": "cancelled",
    "succeeded": "succeeded",
    "failed": "failed",
}
LAST_EVENT_TYPE_BY_STATUS = {
    "open": "rejected",
    "pending": "offered",
    "approved": "approved",
    "succeeded": "succeeded",
    "failed": "failed",
    "cancelled": "closed",
}

CREATE_TASKS_WITH_STATUS_VIEW = """
CREATE VIEW tasks_with_status AS
SELECT
    tasks.*,
    CASE (
        SELECT task_events.type
        FROM task_events
        WHERE task_events.task_id = tasks.id
        ORDER BY task_events.occurred_at DESC, task_events.id DESC
        LIMIT 1
    )
        WHEN 'offered' THEN 'pending'
        WHEN 'approved' THEN 'approved'
        WHEN 'closed' THEN 'cancelled'
        WHEN 'succeeded' THEN 'succeeded'
        WHEN 'failed' THEN 'failed'
        ELSE 'open'
    END AS status
FROM tasks
"""

tasks_table = sa.table(
    "tasks",
    sa.column("id", sa.Integer),
    sa.column("owner_id", sa.Integer),
    sa.column("helper_id", sa.Integer),
    sa.column("helper_offers", sa.String),
    sa.column("status", sa.String),
    sa.column("created_at", sa.DateTime),
    sa.column("updated_at", sa.DateTime),
)
task_events_table = sa.table(
    "task_events",
    sa.column("id", sa.Integer),
    sa.column("task_id", sa.Integer),
    sa.column("type", sa.String),
    sa.column("actor_id", sa.Integer),
    sa.column("helper_id", sa.Integer),
    sa.column("message", sa.String),
    sa.column("occurred_at", sa.DateTime),
)


def _event(
    task_id: int,
    type: str,
    actor_id: int,
    occurred_at: datetime,
    helper_id: int | None = None,
    message: str | None = None,
) -> dict:
    return {
        "task_id": task_id,
        "type": type,
        "actor_id": actor_id,
        "helper_id": helper_id,
        "message": message,
        "occurred_at": occurred_at,
    }


def _task_events(task: sa.Row) -> list[dict]:
    events = [_event(task.id, "created", task.owner_id, task.created_at)]
    for offer in json.loads(task.helper_offers or "[]"):
        offered_at = datetime.fromisoformat(offer["offered_at"])
        if offered_at.tzinfo is not None:
            offered_at = offered_at.astimezone(timezone.utc).replace(tzinfo=None)
        events.append(
            _event(
                task.id,
                "offered",
                offer["user_id"],
                offered_at,
                helper_id=offer["user_id"],
                message=offer["message"],
            )
        )

    if STATUS_BY_EVENT_TYPE[events[-1]["type"]] != task.status:
        # History before task_events is unknown; one closing event makes status derivable.
        event_type = LAST_EVENT_TYPE_BY_STATUS[task.status]
        helper_id = task.helper_id if task.helper_id is not None else events[-1]["helper_id"]
        actor_id = helper_id if event_type == "offered" else task.owner_id
        occurred_at = max(
            [event["occurred_at"] for event in events]
            + ([task.updated_at] if task.updated_at else [])
        )
        events.append(_event(task.id, event_type, actor_id, occurred_at, helper_id=helper_id))
    return events


def _backfill_events() -> None:
    rows = []
    for task in op.get_bind().execute(sa.select(tasks_table)):
        rows.extend(_task_events(task))
    if rows:
        op.bulk_insert(task_events_table, rows)


def _restore_statuses() -> None:
    connection = op.get_bind()
    events = connection.execute(
        sa.select(task_events_table.c.task_id, task_events_table.c.type).order_by(
            task_events_table.c.occurred_at, task_events_table.c.id
        )
    )
    last_event_type = {event.task_id: event.type for event in events}
    for task_id in connection.execute(sa.select(tasks_table.c.id)).scalars():
        status = STATUS_BY_EVENT_TYPE[last_event_type.get(task_id, "created")]
        connection.execute(
            tasks_table.update().where(tasks_table.c.id == task_id).values(status=status)
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("helper_id", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_events_task_id"), "task_events", ["task_id"], unique=False)
    _backfill_events()
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.drop_column("status")
    # ### end Alembic commands ###
    op.execute(CREATE_TASKS_WITH_STATUS_VIEW)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW tasks_with_status")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.add_column(sa.Column("status", sa.VARCHAR(), nullable=True))
    _restore_statuses()
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_index(op.f("ix_task_events_task_id"), table_name="task_events")
    op.drop_table("task_events")
    # ### end Alembic commands ###
