"""

Revision ID: be0b6637ff93
Revises: 19c2afc6d5ff
Create Date: 2026-08-18 21:13:37.462590

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be0b6637ff93"
down_revision: Union[str, Sequence[str], None] = "19c2afc6d5ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("helper_offers", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "helper_offers")
    # ### end Alembic commands ###
