"""add_task_image_paths

Revision ID: 427e4b354446
Revises: be0b6637ff93
Create Date: 2026-09-10 19:51:17.882636

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "427e4b354446"
down_revision: Union[str, Sequence[str], None] = "be0b6637ff93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("image_paths", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "image_paths")
    # ### end Alembic commands ###
