class ServiceException(Exception): ...


class AuthenticationFailed(ServiceException): ...


class ImageNotFound(ServiceException): ...


class PermissionDenied(ServiceException): ...


class MatchServiceException(ServiceException): ...
