class DomainException(Exception): ...


class InvalidTaskAction(DomainException): ...


# Service exceptions


class UserNotFound(Exception): ...


class UserVerificationError(Exception): ...


class UserNotPendingVerification(UserVerificationError): ...


class UserVerificationCodeInvalid(UserVerificationError): ...


class PermissionDenied(Exception): ...


class AuthenticationFailed(Exception): ...

class TaskNotFound(Exception): ...


class NotAnOwner(Exception): ...


class MatchServiceException(Exception): ...

# repository exceptions

class RepositoryException(Exception): ...

