class UserNotFound(Exception): ...


class UserVerificationError(Exception): ...


class UserNotPendingVerification(UserVerificationError): ...


class UserVerificationCodeInvalid(UserVerificationError): ...


class TaskNotFound(Exception): ...
