class DomainException(Exception): ...


class InvalidTaskAction(DomainException): ...


class InvalidLocation(DomainException): ...


class UserVerificationError(DomainException): ...


class UserNotPendingVerification(UserVerificationError): ...


class UserVerificationCodeInvalid(UserVerificationError): ...


# Service exceptions


class ServiceException(Exception): ...


class UserNotFound(ServiceException): ...


class PermissionDenied(ServiceException): ...


class AuthenticationFailed(ServiceException): ...


class TaskNotFound(ServiceException): ...


class NotAnOwner(ServiceException): ...


class MatchServiceException(ServiceException): ...


# repository exceptions


class RepositoryException(Exception): ...
